# Generated by Django 5.1.1 on 2024-09-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'visa'), (2, 'cache'), (3, 'fawry')], default='visa'),
        ),
    ]
