# Generated by Django 5.1.1 on 2024-09-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tax_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
