# Generated by Django 5.1.1 on 2024-09-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_tax_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="price",),
    ]
